---
title: Paperballin
author: GitHub User
email: paperballin@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  It's awesome

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
---
